# Generated by Django 3.2 on 2023-01-10 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='customer/avatars/')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('stripe_payment_id', models.CharField(blank=True, max_length=255)),
                ('stripe_card_last4', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('photo', models.ImageField(upload_to='job/photos/')),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('precessing', 'Processing'), ('picking', 'Picking'), ('delivering', 'Delivering'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='creating', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pickup_address', models.CharField(blank=True, max_length=255)),
                ('pickup_lat', models.FloatField(default=0)),
                ('pickup_lng', models.FloatField(default=0)),
                ('pickup_name', models.CharField(blank=True, max_length=255)),
                ('pickup_phone', models.CharField(blank=True, max_length=50)),
                ('delivery_address', models.CharField(blank=True, max_length=255)),
                ('delivery_lat', models.FloatField(default=0)),
                ('delivery_lng', models.FloatField(default=0)),
                ('delivery_name', models.CharField(blank=True, max_length=255)),
                ('delivery_phone', models.CharField(blank=True, max_length=50)),
                ('duration', models.IntegerField(default=0)),
                ('distance', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
    ]
