# Generated by Django 3.1.3 on 2023-01-15 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230110_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField()),
                ('send_date', models.DateTimeField()),
                ('size_x', models.IntegerField()),
                ('size_y', models.IntegerField()),
                ('size_z', models.IntegerField()),
                ('is_breakable', models.BooleanField(default=False)),
                ('is_perishable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('street_and_number', models.TextField()),
                ('zipcode', models.TextField()),
                ('city', models.TextField()),
                ('country', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('street_and_number', models.TextField()),
                ('zipcode', models.TextField()),
                ('city', models.TextField()),
                ('country', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField()),
                ('expected_deliver_datetime', models.DateTimeField()),
                ('actual_deliver_datetime', models.DateTimeField()),
                ('cost_in_cents', models.IntegerField()),
                ('status', models.TextField(default='REC')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parcel', to='core.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.receiver'),
        ),
        migrations.AddField(
            model_name='order',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.sender'),
        ),
    ]
