# Generated by Django 3.1.3 on 2023-01-18 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230115_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='parcel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='core.parcel'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('creating', 'Cureating'), ('precessing', 'Processing'), ('picking', 'Picking'), ('delivering', 'Delivering'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='creating', max_length=20),
        ),
    ]
