# Generated by Django 3.1.3 on 2023-01-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230118_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='actual_deliver_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='expected_deliver_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
