# Generated by Django 3.1.3 on 2023-01-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230118_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_delivery',
            field=models.JSONField(null=True),
        ),
    ]
