# Generated by Django 3.1.3 on 2023-01-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_last_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='last_delivery',
            field=models.JSONField(default=None, null=True),
        ),
    ]
