# Generated by Django 3.1.3 on 2023-01-18 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230118_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='parcel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='core.parcel'),
        ),
    ]
